B2B/Controllers/PictureController.cs
using B2B.Models.Tree;
using System;
using System.Collections.Generic;
using System.Drawing.Imaging;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace B2B.Controllers
{
    public class PictureController : Controller
    {
        const string rootPath = @"D:\Pazarlama\Gorseller";

        [Authorize]
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public JsonResult GetFileNames()
        {
            List<Child> roots = GetAllDirectories(rootPath);

            var jsonResult = Json(new { data = roots }, JsonRequestBehavior.AllowGet);
            jsonResult.MaxJsonLength = int.MaxValue;
            return jsonResult;
        }

        List<Child> GetAllDirectories(string rootPath)
        {
            List<Child> childs = new List<Child>();
            try
            {
                string[] subdirectories = Directory.GetDirectories(rootPath);
                foreach (string subdirectory in subdirectories)
                {
                    var dirName = new DirectoryInfo(subdirectory).Name;
                    Child root = new Child()
                    {
                        text = dirName,
                        state = new State { opened = false },
                        children = new List<Child>()
                    };

                    childs.Add(root);

                    string[] files = new DirectoryInfo(subdirectory).GetFiles()
                                                      .Select(o => o.Name)
                                                      .ToArray();
                    foreach (var file in files)
                    {
                        root.children.Add(new Child
                        {
                            text = file,
                            state = new State { selected = false },
                            icon = "jstree-file"
                        });
                    }

                    root.children.AddRange(GetAllDirectories(subdirectory));
                }
            }
            catch (UnauthorizedAccessException e)
            {
                Console.WriteLine($"Access denied to folder: {rootPath}. {e.Message}");
            }
            catch (Exception e)
            {
                Console.WriteLine($"An error occurred: {e.Message}");
            }

            return childs;
        }

        [HttpGet]
        public ActionResult DownloadFile(string folderNames, string fileName)
        {
            folderNames = RemoveLastCharacter(folderNames);

            string filePath = string.Format(rootPath + "\\{0}\\{1}", folderNames, fileName);

            byte[] fileBytes = System.IO.File.ReadAllBytes(filePath);

            return File(fileBytes,
                  System.Net.Mime.MediaTypeNames.Image.Jpeg,
                  fileName);
        }

        string RemoveLastCharacter(string input)
        {
            if (string.IsNullOrEmpty(input) || input.Length == 1)
            {
                return string.Empty; // Return empty if input is null, empty, or only one character long
            }

            return input.Substring(0, input.Length - 1);
        }
    }
}

B2B/Views/Picture/Index.cshtml
@{
    ViewBag.Title = "Görseller";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div id="jCrumbs" class="breadCrumb module">
    <ul>
        <li>
            <a href="/Home/Index">
                <i class="glyphicon glyphicon-home"></i>
            </a>
        </li>
        <li style="background: none;">
            <span style="width: 70px;"><a href="#" style="width: 80px;">Dökümanlar</a></span>
            <div class="chevronOverlay" style="display: block;"></div>
        </li>
        <li>
            Görseller
        </li>
    </ul>
</div>

<div class="row">
    <div class="col-sm-12 col-md-12">
        <h3 class="heading">
            Görseller
            <a id="btn-download" class="btn btn-default btn-etiket" style="display:none">
                <i class="fa fa-download"></i>
                İndir
            </a>
        </h3>
    </div>

    <div class="col-sm-12 col-md-12">
        <div class="col-sm-6 col-md-6 col-lg-6">
            <div id="tree"></div>
        </div>

        <div class="col-sm-6 col-md-6 col-lg-6">
            <div id="pdf-container" style="display:none">
                <img id="img-iframe" class="active float-right">
            </div>
        </div>
    </div>
</div>

@section Scripts{
    <script>
        $(document).ready(function() {
             $.ajax({
                    url: '@Url.Action("GetFileNames", "Picture")',
                    type: 'POST',
                    contentType: 'application/json',
                    success: function(response) {
                       $('#tree')
                        .on("changed.jstree", function (e, data) {
                            if (data && data.selected && data.selected.length) {
                                var selectedNode = data.node;
                                var nodeText = selectedNode.text;
                                var extension = nodeText.substring(nodeText.lastIndexOf('.') + 1);
                                console.log(selectedNode);
                                if (selectedNode.parent != "#" && selectedNode.icon !=true) {
                                    var dirNames = "";
                                    var parentNodes = getAllParentNodes(selectedNode);
                                    var reversedParents = parentNodes.reverse();
                                    $.each(reversedParents, function (index, parent) {
                                        dirNames += parent.text + '/';
                                    });

                                    $('#btn-download').attr('href', '/Picture/DownloadFile?folderNames=' + dirNames + '&fileName=' + selectedNode.text);
                                    $('#btn-download').show();

                                    if (extension =="tif") {
                                        var myLink = document.getElementById('btn-download');
                                        myLink.click();
                                    }
                                    else {
                                        $('#img-iframe').attr('src', 'https://b2b.alfemo.com.tr/pazarlama/gorseller/' + dirNames + selectedNode.text);
                                        $('#pdf-container').show();
                                    }
                                }
                            }
                        })
                        .jstree({
                            'core': {
                                'data': response.data
                            }
                        });
                    },
                    error: function(xhr, status, error) {
                        alert('Error: ' + error);
                    }
             });

            function getAllParentNodes(node) {
                var parents = [];
                var parent = $('#tree').jstree().get_parent(node);

                while (parent && parent !== "#") {
                    parent = $('#tree').jstree().get_node(parent);
                    parents.push(parent);
                    parent = $('#tree').jstree().get_parent(parent);
                }

                return parents;
            }
        });
    </script>
}